apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: rancher-query-job
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: rancher-query-sa
          containers:
          - name: rancher-query
            image: wrkode/rancher-scriba:dev
            imagePullPolicy: Always
            env:
            - name: RANCHER_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: rancher-api-secrets
                  key: RANCHER_SERVER_URL
            - name: RANCHER_TOKEN_KEY
              valueFrom:
                secretKeyRef:
                  name: rancher-api-secrets
                  key: RANCHER_TOKEN_KEY
          restartPolicy: OnFailure